### ISSUE TITLE
[PYI-2792:ERROR] Failed to execute script '__main__' due to unhandled exception!

### ISSUE THREAD

**Issue by throwaway242685** [gdl-org/builds#2]
```
Traceback (most recent call last):
  File "gallery_dl\__main__.py", line 20, in <module>
  File "gallery_dl\__init__.py", line 353, in main
  File "gallery_dl\job.py", line 297, in __init__
  File "gallery_dl\job.py", line 60, in __init__
ImportError: cannot import name 'parse' from 'gallery_dl.actions' (C:\Users\PC\AppData\Local\Temp\_MEI10082\gallery_dl\actions.py)
[PYI-2792:ERROR] Failed to execute script '__main__' due to unhandled exception!
```

hi, I'm getting this error with the latest build of `gallery-dl_windows_x86.exe`

it just crashes right after that:(

**Comment by mikf** [comment]
That's a bug caused by commit https://github.com/mikf/gallery-dl/commit/bccf467d19ee58153474265aef76e427fa23e7c3.

I'm 100% sure I updated and tested this before pushing this commit, but apparently not.
Oh well ... will be fixed in the next build.

**Comment by mikf** [comment]
https://github.com/mikf/gallery-dl/commit/232e30f64e998cf06347c1103a592c11f3bde162
